"""
Django settings for rapper project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Configure ALLOWED_HOSTS dynamically from environment variable (comma-separated string).
# Subdomain wildcards use a leading dot -- "*.up.railway.app" matches nothing.
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,.up.railway.app,*')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]

# Configure CSRF_TRUSTED_ORIGINS for Railway HTTPS and local testing
csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS', 'https://*.up.railway.app,http://localhost:8000,http://127.0.0.1:8000')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_htmx',
    'django_cotton',

    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'chat.middleware.ClerkJWTMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'rapper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rapper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        # Connections are persistent and per-thread, so the threaded Gunicorn
        # worker holds one per active thread; health checks recycle any that
        # went stale between requests instead of raising on first use.
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

CLERK_PUBLISHABLE_KEY = os.getenv('CLERK_PUBLISHABLE_KEY')
CLERK_JWKS_URL = os.getenv('CLERK_JWKS_URL')

OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
OPENROUTER_MODEL = os.getenv('OPENROUTER_MODEL', 'google/gemini-2.5-flash-lite')
# Chat titles are a short, throwaway call, so they run on their own small
# instruction-tuned model rather than borrowing the chat one -- which may well be
# a reasoning model, and those spend their budget thinking before they answer.
# `or` rather than a getenv default: the key is present but blank in .env.example,
# and an empty string would otherwise be taken as a real model name.
# The `:free` slug this used to point at is gone -- OpenRouter now answers it
# with a 404 naming the paid model -- and a title is a few hundred tokens, so the
# paid tier costs a rounding error per conversation. Which makes price close to
# irrelevant in the choice: what separates models here is whether they return a
# consistently cased three-to-six word phrase, since a sidebar of titles that
# disagree about capitalisation reads as broken, and anything long or chatty is
# thrown away by _clean_title and leaves the chat named "New Chat".
OPENROUTER_TITLE_MODEL = os.getenv('OPENROUTER_TITLE_MODEL') or 'mistralai/mistral-nemo'

def _int_env(name, default):
    """An integer setting from the environment, tolerant of a key that is present
    but blank -- which is how .env.example ships every optional value, and what
    int('') would otherwise turn into a crash at import time."""
    try:
        return int(os.getenv(name) or default)
    except ValueError:
        print(f'{name} is not a number, falling back to {default}')
        return default


# How many model -> tool -> model round trips one reply may take. Every hop is a
# billed request, so this is the ceiling on what a single message can cost when
# the model keeps searching instead of answering.
CHAT_AGENT_RECURSION_LIMIT = _int_env('CHAT_AGENT_RECURSION_LIMIT', 8)

# The evaluator: a second model that scores the user's prompt and the assistant's
# answer, and whose critiques are fed back into later turns (see chat/evaluator.py).
# It costs two extra model calls per message, so it is a switch rather than a
# constant -- turning it off restores the plain one-call-per-message behaviour.
CHAT_EVALUATOR_ENABLED = os.getenv('CHAT_EVALUATOR_ENABLED', 'true').lower() not in (
    '0', 'false', 'no', 'off')
# Critiques are short and highly structured, so this follows the title model in
# preferring a non-reasoning model over the one answering the user. Not the
# smallest one going, though: this one has to hold a scoring rubric and write a
# usable critique, which is more than naming a chat asks for.
OPENROUTER_EVALUATOR_MODEL = (
    os.getenv('OPENROUTER_EVALUATOR_MODEL') or 'meta-llama/llama-3.3-70b-instruct')

# How much of the conversation each critique is shown. A critic that cannot see
# what a follow-up refers to reports the answer as invented, so these are the
# limits to raise if critiques start complaining about missing context. The
# total is a hard ceiling: without it the other two multiply.
CHAT_EVALUATOR_CONTEXT_TURNS = _int_env('CHAT_EVALUATOR_CONTEXT_TURNS', 10)
CHAT_EVALUATOR_CONTEXT_CHARS = _int_env('CHAT_EVALUATOR_CONTEXT_CHARS', 2000)
CHAT_EVALUATOR_CONTEXT_TOTAL_CHARS = _int_env('CHAT_EVALUATOR_CONTEXT_TOTAL_CHARS', 9000)
# Output ceiling for one critique, reasoning tokens included. Worth raising if
# critiques go missing: a reasoning model spends this budget thinking first, and
# running out mid-thought returns an empty string rather than an error.
CHAT_EVALUATOR_MAX_TOKENS = _int_env('CHAT_EVALUATOR_MAX_TOKENS', 1200)

# Langfuse tracing (see chat/tracing.py). Entirely optional: with no keys set
# nothing is sent anywhere and the app behaves exactly as it did before. Keys
# come from the Langfuse project under Settings -> API Keys.
LANGFUSE_PUBLIC_KEY = os.getenv('LANGFUSE_PUBLIC_KEY')
LANGFUSE_SECRET_KEY = os.getenv('LANGFUSE_SECRET_KEY')
# Region-specific, and not interchangeable: the EU, US and Japan clouds are
# separate deployments, and a key pair only authenticates against the one it was
# issued by. Defaults to EU, which is where a plain cloud.langfuse.com signup
# lands.
LANGFUSE_BASE_URL = os.getenv('LANGFUSE_BASE_URL') or 'https://cloud.langfuse.com'
# Keeps traces from a laptop out of the dashboards that describe real traffic.
# Derived from DEBUG rather than required, so local runs are labelled correctly
# without anyone having to remember to set it.
LANGFUSE_ENVIRONMENT = (
    os.getenv('LANGFUSE_TRACING_ENVIRONMENT')
    or ('development' if DEBUG else 'production')
)

# How much of a conversation is replayed to the model on each turn. The whole
# history is re-sent every time, so left unbounded a conversation's input cost
# grows with the square of its length; this caps it. Counted in tokens rather
# than messages because a searched answer runs several times the length of a
# plain one, so a message count would be a budget that swings with what the user
# happened to ask. Tunable without a deploy: too low and follow-up questions
# stop finding what they refer to, too high and long chats get expensive.
CHAT_HISTORY_TOKEN_BUDGET = int(os.getenv('CHAT_HISTORY_TOKEN_BUDGET') or 4000)

# Tavily web search, exposed to the assistant as a tool (see chat/tools.py).
# Left blank rather than required: without it the tool reports itself unavailable
# and the assistant answers from what it knows, so the app still runs.
TAVILY_API_KEY = os.getenv('TAVILY_API', '')

# Polar.sh billing
POLAR_ACCESS_TOKEN = os.getenv('POLAR_ACCESS_TOKEN')
POLAR_WEBHOOK_SECRET = os.getenv('POLAR_WEBHOOK_SECRET')
POLAR_SERVER = os.getenv('POLAR_SERVER', 'sandbox')  # 'sandbox' or 'production'
POLAR_PRODUCT_BASIC_MONTHLY = os.getenv('POLAR_PRODUCT_BASIC_MONTHLY')
POLAR_PRODUCT_BASIC_ANNUAL = os.getenv('POLAR_PRODUCT_BASIC_ANNUAL')
POLAR_PRODUCT_PRO_MONTHLY = os.getenv('POLAR_PRODUCT_PRO_MONTHLY')
POLAR_PRODUCT_PRO_ANNUAL = os.getenv('POLAR_PRODUCT_PRO_ANNUAL')