# Generated by Django 6.0.7 on 2026-07-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
