# Generated by Django 6.0.7 on 2026-08-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='stop_requested',
            field=models.BooleanField(default=False),
        ),
    ]
