# Generated by Django 6.0.7 on 2026-08-04 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_stop_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('usage_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('polar_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('polar_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=10)),
                ('billing_interval', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('free', 'Free'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='free', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
