# Generated by Django 6.0.7 on 2026-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
