# Generated by Django 6.0.7 on 2026-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_subscriber_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='pending_billing_interval',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='pending_plan',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
