# Generated by Django 6.0.7 on 2026-08-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_subscriber_pending_billing_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='critique_of',
            field=models.CharField(blank=True, choices=[('prompt', 'Prompt'), ('response', 'Response')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='message',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('evaluator', 'Evaluator')], max_length=10),
        ),
    ]
